# Generated by Django 3.2.13 on 2022-06-13 03:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 3, 25, 56, 230941, tzinfo=utc)),
        ),
    ]
